<?php

function my_acf_google_map_api($api) {
  $api['key'] = 'AIzaSyBsLJ9ehLPiECFfRDQtgtOh51GDlqXKAGE';
  return $api;
}
add_filter('acf/fields/google_map/api', 'my_acf_google_map_api');

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_588b782a79158',
	'title' => 'Contatti',
	'fields' => array (
		array (
			'key' => 'field_588b7a7d67c18',
			'label' => 'Form',
			'name' => 'contact_form',
			'type' => 'gravity_forms_field',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_multiple' => 0,
			'allow_null' => 0,
		),
		array (
			'key' => 'field_588f4ba70b1d1',
			'label' => 'Mappa',
			'name' => 'contact_map',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'height' => 333,
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
		),
		array (
			'key' => 'field_588f4bf60b1d2',
			'label' => 'Corpo',
			'name' => 'contact_body',
			'type' => 'wysiwyg',
			'instructions' => 'Utilizzare la scala di partenza uguale o minore a H3 per i titoli',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'default_value' => '',
			'delay' => 0,
		),
		array (
			'key' => 'field_588f4c99ae47f',
			'label' => 'Informazioni',
			'name' => 'contact_information',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi',
			'collapsed' => 'field_588f4cc2ae480',
			'sub_fields' => array (
				array (
					'key' => 'field_588f4cc2ae480',
					'label' => 'Titolo',
					'name' => 'contact_information_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_588f4cd5ae481',
					'label' => 'Corpo',
					'name' => 'contact_information_body',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'default_value' => '',
					'delay' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-pages/contact.php',
			),
		),
	),
	'menu_order' => -1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5892691c0f2dc',
	'title' => 'Articoli',
	'fields' => array (
		array (
			'key' => 'field_589269d16bf1f',
			'label' => 'Banner',
			'name' => 'posts_banner_if',
			'type' => 'true_false',
			'instructions' => 'Verrà abilitato nei articoli.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'message' => 'Abilitare il banner?',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_58926a4a6bf20',
			'label' => 'Titolo',
			'name' => 'posts_banner_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_589269d16bf1f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58926a676bf21',
			'label' => 'Testo',
			'name' => 'posts_banner_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_589269d16bf1f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
		),
		array (
			'key' => 'field_58926a7e6bf22',
			'label' => 'Link',
			'name' => 'posts_banner_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_589269d16bf1f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'posts_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5891fac631c3f',
	'title' => 'Location',
	'fields' => array (
		array (
			'key' => 'field_58a2e26d34ed5',
			'label' => 'Galleria',
			'name' => 'gallery',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi galleria',
			'sub_fields' => array (
				array (
					'key' => 'field_58a2e26e34ed6',
					'label' => 'Grande',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_58a2e5095f226',
					'label' => 'Immagine',
					'name' => 'gallery__large__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_58a2e26e34edb',
					'label' => 'Media',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_58a2e26e34edc',
					'label' => 'Immagine',
					'name' => 'gallery__medium__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_58a2e26e34edf',
					'label' => 'Piccola 1 di 2',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_58a2e26e34ee1',
					'label' => 'Immagine',
					'name' => 'gallery__small__1__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_58a2e26e34ee5',
					'label' => 'Piccola 2 di 2',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_58a2e31a5f225',
					'label' => 'Immagine',
					'name' => 'gallery__small__2__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_58a2e26e34eeb',
					'label' => 'Layout',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_58a2e26e34eec',
					'label' => 'Combinazione',
					'name' => 'gallery__layout',
					'type' => 'radio',
					'instructions' => 'Consente di ordinare le immagini',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'one' => '1',
						'two' => '2',
						'three' => '3',
						'four' => '4',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'one',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
			),
		),
		array (
			'key' => 'field_58a1d1293b429',
			'label' => 'Banner',
			'name' => 'banner',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_58a1d16c3b42b',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi Banner',
			'sub_fields' => array (
				array (
					'key' => 'field_58a1d1543b42a',
					'label' => 'Immagine',
					'name' => 'banner_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_58a1d16c3b42b',
					'label' => 'Titolo',
					'name' => 'banner_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58a1d1963b42c',
					'label' => 'Testo',
					'name' => 'banner_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
				array (
					'key' => 'field_58a1d1b73b42d',
					'label' => 'Link',
					'name' => 'banner_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_58a1d22d7ce3f',
					'label' => 'Posizione',
					'name' => 'banner_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Sinistra',
						'right' => 'Destra',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'left',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-pages/location.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5890bf83cff0d',
	'title' => 'Opzioni',
	'fields' => array (
		array (
			'key' => 'field_58aedbdc134dd',
			'label' => 'Generali',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5890c714540fd',
			'label' => 'Bottone',
			'name' => 'options_contact',
			'type' => 'page_link',
			'instructions' => 'Seleziona la pagina che verrà associata al bottone nel header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
		),
		array (
			'key' => 'field_5890bfbea8760',
			'label' => 'Telefono',
			'name' => 'options_phone',
			'type' => 'text',
			'instructions' => 'Inserire il numero senza spazi, insieme al prefisso es. “+391234567890”.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5890c0aea8762',
			'label' => 'Email',
			'name' => 'options_email',
			'type' => 'text',
			'instructions' => 'Inserire la email es. “info@landhocoworking.com”.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5890c0daa8763',
			'label' => 'Indirizzo',
			'name' => 'options_address',
			'type' => 'text',
			'instructions' => 'Inserire indirizzo es. “Via del Corso 280, 00187 Rome Italy”.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5890c15aa8764',
			'label' => 'Facebook',
			'name' => 'options_facebook',
			'type' => 'text',
			'instructions' => 'Inserire url diretto alla pagina Facebook.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5890c171a8765',
			'label' => 'Instagram',
			'name' => 'options_instagram',
			'type' => 'text',
			'instructions' => 'Inserire url diretto al canale Instagram.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58aedbe8134de',
			'label' => 'Cookies',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58aedbf0134df',
			'label' => 'Testo',
			'name' => 'options_cookies_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_58aedc0a134e0',
			'label' => 'Link',
			'name' => 'options_cookies_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_58aef8c35e39e',
			'label' => 'Privacy',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58aef8d25e39f',
			'label' => 'Titolo',
			'name' => 'options_privacy_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58aef9085e3a0',
			'label' => 'Link',
			'name' => 'options_privacy_link',
			'type' => 'url',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58930bba73e1b',
	'title' => 'Piani',
	'fields' => array (
		array (
			'key' => 'field_58932d184dd00',
			'label' => 'Partners',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58932d8de5c13',
			'label' => 'Titolo',
			'name' => 'plans_banner_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58932da7e5c14',
			'label' => 'Testo',
			'name' => 'plans_banner_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
		),
		array (
			'key' => 'field_58932dd23508d',
			'label' => 'Link',
			'name' => 'plans_banner_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
		),
		array (
			'key' => 'field_589321ed1e5ae',
			'label' => 'Partners',
			'name' => 'plans_partners',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Aggiungi partner',
			'collapsed' => 'field_589323761e5b0',
			'sub_fields' => array (
				array (
					'key' => 'field_589322371e5af',
					'label' => 'Immagine',
					'name' => 'plans_partners_image',
					'type' => 'file',
					'instructions' => 'Immagine a 1:1 con dimensioni 256x256px. Formati supportati: svg (consigliato), png, jpg, jpeg, gif',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'svg,png,jpg,jpeg,gif',
				),
				array (
					'key' => 'field_589323761e5b0',
					'label' => 'Titolo',
					'name' => 'plans_partners_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_58932d284dd01',
					'label' => 'Link',
					'name' => 'plans_partners_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-pages/plans.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_589314f568898',
	'title' => 'Piano',
	'fields' => array (
		array (
			'key' => 'field_589339a20c8fc',
			'label' => 'Sottotitolo',
			'name' => 'plan_lead',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
		),
		array (
			'key' => 'field_58933b676ac7d',
			'label' => 'Prezzo',
			'name' => 'plan_price',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58933d09d5cbc',
			'label' => 'Form',
			'name' => 'plan_form',
			'type' => 'gravity_forms_field',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_multiple' => 0,
			'allow_null' => 0,
		),
		array (
			'key' => 'field_58933c66df23a',
			'label' => 'Testo',
			'name' => 'plan_text',
			'type' => 'wysiwyg',
			'instructions' => 'Utilizzare la scala di partenza uguale o minore a H3 per i titoli',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'default_value' => '',
			'delay' => 0,
		),
		array (
			'key' => 'field_58933bbaa7b8f',
			'label' => 'Caratteristiche',
			'name' => 'plan_features',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi caratteristica',
			'collapsed' => 'field_58933be0a7b90',
			'sub_fields' => array (
				array (
					'key' => 'field_58933be0a7b90',
					'label' => 'Titolo',
					'name' => 'plan_features_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_58933bf1a7b91',
					'label' => 'Testo',
					'name' => 'plan_features_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 2,
				),
			),
		),
		array (
			'key' => 'field_58933e71f47e7',
			'label' => 'Evidenziato',
			'name' => 'plan_featured',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'message' => 'Evidenziare il piano corrente?',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'piano',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58921225b53bc',
	'title' => 'Servizi',
	'fields' => array (
		array (
			'key' => 'field_5892123450071',
			'label' => 'Servizi',
			'name' => 'services',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi servizio',
			'collapsed' => 'field_5892125250072',
			'sub_fields' => array (
				array (
					'key' => 'field_5892127f50074',
					'label' => 'Immagine',
					'name' => 'services_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_5892125250072',
					'label' => 'Titolo',
					'name' => 'services_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_5892126450073',
					'label' => 'Testo',
					'name' => 'services_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 2,
				),
			),
		),
		array (
			'key' => 'field_589214f7f81a3',
			'label' => 'Banner',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_5892158454365',
			'label' => 'Banner',
			'name' => 'services_banner_if',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'message' => 'Abilitare il banner?',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_58921526aec0a',
			'label' => 'Titolo',
			'name' => 'services_banner_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5892158454365',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58921546aec0b',
			'label' => 'Testo',
			'name' => 'services_banner_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5892158454365',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
		),
		array (
			'key' => 'field_58921555aec0c',
			'label' => 'Link',
			'name' => 'services_banner_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5892158454365',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-pages/services.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_589264c80aacb',
	'title' => 'Articolo',
	'fields' => array (
		array (
			'key' => 'field_589264d1091be',
			'label' => 'Sottotitolo',
			'name' => 'post_lead',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 4,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_589b39c57657b',
	'title' => 'Bacheca',
	'fields' => array (
		array (
			'key' => 'field_589b39e6a74fb',
			'label' => 'Bacheca',
			'name' => 'board',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi scheda',
			'collapsed' => 'field_589b3af0a7502',
			'sub_fields' => array (
				array (
					'key' => 'field_589b3a82a74fd',
					'label' => 'Grande',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_589b3a0ca74fc',
					'label' => 'Immagine',
					'name' => 'board__large__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_589b3af0a7502',
					'label' => 'Titolo',
					'name' => 'board__large__title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_589b3b0ca7503',
					'label' => 'Testo',
					'name' => 'board__large__text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 2,
				),
				array (
					'key' => 'field_589b3b27a7504',
					'label' => 'Link',
					'name' => 'board__large__link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'allow_archives' => 0,
				),
				array (
					'key' => 'field_589b3a91a74fe',
					'label' => 'Medio',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_589b3b58a7505',
					'label' => 'Immagine',
					'name' => 'board__medium__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_589b3b73a7506',
					'label' => 'Titolo',
					'name' => 'board__medium__title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_589b3b76a7507',
					'label' => 'Link',
					'name' => 'board__medium__link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'post',
						1 => 'page',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'allow_archives' => 0,
				),
				array (
					'key' => 'field_589b3a96a74ff',
					'label' => 'Piccolo 1 di 2',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_589b3baca7508',
					'label' => 'Contenuto',
					'name' => 'board__small__1__type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'vertical',
					'choices' => array (
						'image' => 'Immagine',
						'video' => 'Video',
						'text' => 'Testo',
					),
					'default_value' => 'image',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
				),
				array (
					'key' => 'field_589b3bf4a7509',
					'label' => 'Immagine',
					'name' => 'board__small__1__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'image',
							),
						),
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_589b3bf7a750a',
					'label' => 'Titolo',
					'name' => 'board__small__1__title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'image',
							),
						),
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'video',
							),
						),
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_589b3bf9a750b',
					'label' => 'Testo',
					'name' => 'board__small__1__text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 2,
				),
				array (
					'key' => 'field_589b3bfba750c',
					'label' => 'Link',
					'name' => 'board__small__1__link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'image',
							),
						),
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'video',
							),
						),
						array (
							array (
								'field' => 'field_589b3baca7508',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'post',
						1 => 'page',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'allow_archives' => 0,
				),
				array (
					'key' => 'field_589b3d7d1c1ea',
					'label' => 'Piccolo 2 di 2',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_589b3db21c1eb',
					'label' => 'Contenuto',
					'name' => 'board__small__2__type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'vertical',
					'choices' => array (
						'image' => 'Immagine',
						'video' => 'Video',
						'text' => 'Testo',
					),
					'default_value' => 'image',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
				),
				array (
					'key' => 'field_589b3db81c1ec',
					'label' => 'Immagine',
					'name' => 'board__small__2__image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'image',
							),
						),
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
				),
				array (
					'key' => 'field_589b3dbd1c1ed',
					'label' => 'Titolo',
					'name' => 'board__small__2__title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'image',
							),
						),
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'video',
							),
						),
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_589b3dc41c1ee',
					'label' => 'Testo',
					'name' => 'board__small__2__text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 2,
				),
				array (
					'key' => 'field_589b3dc91c1ef',
					'label' => 'Link',
					'name' => 'board__small__2__link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'image',
							),
						),
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'video',
							),
						),
						array (
							array (
								'field' => 'field_589b3db21c1eb',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'post',
						1 => 'page',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'allow_archives' => 0,
				),
				array (
					'key' => 'field_589b3e46ab2f9',
					'label' => 'Layout',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_589b3e838776b',
					'label' => 'Combinazione',
					'name' => 'board__layout',
					'type' => 'radio',
					'instructions' => 'Consente di ordinare le schede',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'vertical',
					'choices' => array (
						'one' => '1',
						'two' => '2',
						'three' => '3',
						'four' => '4',
					),
					'default_value' => 'one',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-pages/home.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58925cd10f21d',
	'title' => 'Pagine',
	'fields' => array (
		array (
			'key' => 'field_58925cddf19a2',
			'label' => 'Sottotitolo',
			'name' => 'page_lead',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 4,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'posts_page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
