<?php

function my_acf_google_map_api($api) {
  $api['key'] = 'AIzaSyBsLJ9ehLPiECFfRDQtgtOh51GDlqXKAGE';
  return $api;
}
add_filter('acf/fields/google_map/api', 'my_acf_google_map_api');

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58925cd10f21d',
	'title' => 'Pagine',
	'fields' => array (
		array (
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 4,
			'key' => 'field_58925cddf19a2',
			'label' => 'Sottotitolo',
			'name' => 'page_lead',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'posts_page',
			),
		),
	),
	'menu_order' => -9,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_589264c80aacb',
	'title' => 'Articolo',
	'fields' => array (
		array (
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 4,
			'key' => 'field_589264d1091be',
			'label' => 'Sottotitolo',
			'name' => 'post_lead',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => -1,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_588b782a79158',
	'title' => 'Contatti',
	'fields' => array (
		array (
			'allow_multiple' => 0,
			'allow_null' => 0,
			'key' => 'field_588b7a7d67c18',
			'label' => 'Form',
			'name' => 'contact_form',
			'type' => 'gravity_forms_field',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'height' => 333,
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'key' => 'field_588f4ba70b1d1',
			'label' => 'Mappa',
			'name' => 'contact_map',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'default_value' => '',
			'delay' => 0,
			'key' => 'field_588f4bf60b1d2',
			'label' => 'Corpo',
			'name' => 'contact_body',
			'type' => 'wysiwyg',
			'instructions' => 'Utilizzare la scala di partenza uguale o minore a H3 per i titoli',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'sub_fields' => array (
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_588f4cc2ae480',
					'label' => 'Titolo',
					'name' => 'contact_information_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'default_value' => '',
					'delay' => 0,
					'key' => 'field_588f4cd5ae481',
					'label' => 'Corpo',
					'name' => 'contact_information_body',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi',
			'collapsed' => 'field_588f4cc2ae480',
			'key' => 'field_588f4c99ae47f',
			'label' => 'Informazioni',
			'name' => 'contact_information',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-pages/contact.php',
			),
		),
	),
	'menu_order' => -1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5892691c0f2dc',
	'title' => 'Articoli',
	'fields' => array (
		array (
			'default_value' => 0,
			'message' => 'Abilitare il banner?',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_589269d16bf1f',
			'label' => 'Banner',
			'name' => 'posts_banner_if',
			'type' => 'true_false',
			'instructions' => 'Verrà abilitato nei articoli.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58926a4a6bf20',
			'label' => 'Titolo',
			'name' => 'posts_banner_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_589269d16bf1f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
			'key' => 'field_58926a676bf21',
			'label' => 'Testo',
			'name' => 'posts_banner_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_589269d16bf1f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
			'key' => 'field_58926a7e6bf22',
			'label' => 'Link',
			'name' => 'posts_banner_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_589269d16bf1f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'posts_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5890cdd6e861f',
	'title' => 'Home',
	'fields' => array (
		array (
			'layouts' => array (
				array (
					'key' => '5891e9654c049',
					'name' => 'home_card_large',
					'label' => 'Grande',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg',
							'key' => 'field_5891ea0f23060',
							'label' => 'Immagine',
							'name' => 'home_card_large_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'key' => 'field_5891e9d52305e',
							'label' => 'Titolo',
							'name' => 'home_card_large_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 2,
							'key' => 'field_5891e9ec2305f',
							'label' => 'Testo',
							'name' => 'home_card_large_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'post_type' => array (
								0 => 'post',
								1 => 'page',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'allow_archives' => 0,
							'key' => 'field_5891ea4623061',
							'label' => 'Link',
							'name' => 'home_card_large_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5891eaa8b5bcd',
					'name' => 'home_card_medium',
					'label' => 'Media',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'key' => 'field_5891eab5b5bce',
							'label' => 'Immagine',
							'name' => 'home_card_medium_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'key' => 'field_5891eaeda3bac',
							'label' => 'Titolo',
							'name' => 'home_card_medium_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'post_type' => array (
								0 => 'page',
								1 => 'post',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'allow_archives' => 0,
							'key' => 'field_5891eb00a3bad',
							'label' => 'Link',
							'name' => 'home_card_medium_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5891eb39a3bae',
					'name' => 'home_card_small',
					'label' => 'Piccola',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'layout' => 'vertical',
							'choices' => array (
								'image' => 'Immagine',
								'video' => 'Video',
								'text' => 'Testo',
							),
							'default_value' => 'image',
							'other_choice' => 0,
							'save_other_choice' => 0,
							'allow_null' => 0,
							'return_format' => 'value',
							'key' => 'field_5891eba8a3baf',
							'label' => 'Tipologia',
							'name' => 'home_card_small_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg',
							'key' => 'field_5891ec20a3bb0',
							'label' => 'Immagine',
							'name' => 'home_card_small_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'image',
									),
								),
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'key' => 'field_5891ec6da3bb3',
							'label' => 'Titolo',
							'name' => 'home_card_small_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'image',
									),
								),
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'video',
									),
								),
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'text',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 2,
							'key' => 'field_5891eca2a3bb4',
							'label' => 'Testo',
							'name' => 'home_card_small_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'text',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'post_type' => array (
								0 => 'page',
								1 => 'post',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'allow_archives' => 0,
							'key' => 'field_5891ecd4a3bb5',
							'label' => 'Link',
							'name' => 'home_card_small_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'image',
									),
								),
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'video',
									),
								),
								array (
									array (
										'field' => 'field_5891eba8a3baf',
										'operator' => '==',
										'value' => 'text',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Aggiungi scheda',
			'key' => 'field_5891e8fa2305d',
			'label' => 'Bacheca',
			'name' => 'home_board',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-pages/home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5891fac631c3f',
	'title' => 'Location',
	'fields' => array (
		array (
			'layouts' => array (
				array (
					'key' => '5891e9654c049',
					'name' => 'location_image_large',
					'label' => 'Grande',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'layout' => 'vertical',
							'choices' => array (
								'image' => 'Immagine',
								'video' => 'Video',
							),
							'default_value' => 'image',
							'other_choice' => 0,
							'save_other_choice' => 0,
							'allow_null' => 0,
							'return_format' => 'value',
							'key' => 'field_5891ff7d2fe2a',
							'label' => 'Tipologia',
							'name' => 'location_image_large_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg',
							'key' => 'field_5891fac63806e',
							'label' => 'Immagine',
							'name' => 'location_image_large_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5891ff7d2fe2a',
										'operator' => '==',
										'value' => 'image',
									),
								),
								array (
									array (
										'field' => 'field_5891ff7d2fe2a',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'url',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'mp4',
							'key' => 'field_5891ffc82fe2b',
							'label' => 'Video',
							'name' => 'location_image_large_video',
							'type' => 'file',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5891ff7d2fe2a',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5892016167d5f',
					'name' => 'location_image_medium',
					'label' => 'Media',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'layout' => '',
							'choices' => array (
								'image' => 'Immagine',
								'video' => 'Video',
							),
							'default_value' => 'image',
							'other_choice' => 0,
							'save_other_choice' => 0,
							'allow_null' => 0,
							'return_format' => '',
							'key' => 'field_5892016167d60',
							'label' => 'Tipologia',
							'name' => 'location_image_medium_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => '',
							'preview_size' => 'thumbnail',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg',
							'key' => 'field_5892016167d61',
							'label' => 'Immagine',
							'name' => 'location_image_medium_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5892016167d60',
										'operator' => '==',
										'value' => 'image',
									),
								),
								array (
									array (
										'field' => 'field_5892016167d60',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => '',
							'library' => '',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'mp4',
							'key' => 'field_5892016167d62',
							'label' => 'Video',
							'name' => 'location_image_medium_video',
							'type' => 'file',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5892016167d60',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5892018c67d63',
					'name' => 'location_image_small',
					'label' => 'Piccola',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'layout' => 'vertical',
							'choices' => array (
								'image' => 'Immagine',
								'video' => 'Video',
							),
							'default_value' => 'image',
							'other_choice' => 0,
							'save_other_choice' => 0,
							'allow_null' => 0,
							'return_format' => 'value',
							'key' => 'field_5892018c67d64',
							'label' => 'Tipologia',
							'name' => 'location_image_small_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg',
							'key' => 'field_5892018c67d65',
							'label' => 'Immagine',
							'name' => 'location_image_small_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5892018c67d64',
										'operator' => '==',
										'value' => 'image',
									),
								),
								array (
									array (
										'field' => 'field_5892018c67d64',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'url',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'mp4',
							'key' => 'field_5892018c67d66',
							'label' => 'Video',
							'name' => 'location_image_small_video',
							'type' => 'file',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5892018c67d64',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Aggiungi immagine',
			'key' => 'field_5891fac635a37',
			'label' => 'Galleria',
			'name' => 'location_gallery',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layouts' => array (
				array (
					'key' => '5891e9654c049',
					'name' => 'location_banner_left',
					'label' => 'Sinistro',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'return_format' => '',
							'preview_size' => 'thumbnail',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg',
							'key' => 'field_5892023b9a1a5',
							'label' => 'Immagine',
							'name' => 'location_banner_left_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'key' => 'field_589202c89a1ad',
							'label' => 'Titolo',
							'name' => 'location_banner_left_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 4,
							'key' => 'field_589202db9a1ae',
							'label' => 'Testo',
							'name' => 'location_banner_left_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'placeholder' => '',
							'key' => 'field_589202fd9a1af',
							'label' => 'Link',
							'name' => 'location_banner_left_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5892032b9a1b0',
					'name' => 'location_banner_right',
					'label' => 'Destro',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg',
							'key' => 'field_5892032b9a1b1',
							'label' => 'Immagine',
							'name' => 'location_banner_right_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'key' => 'field_5892032b9a1b2',
							'label' => 'Titolo',
							'name' => 'location_banner_right_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 4,
							'key' => 'field_5892032b9a1b3',
							'label' => 'Testo',
							'name' => 'location_banner_right_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'placeholder' => '',
							'key' => 'field_5892032b9a1b4',
							'label' => 'Link',
							'name' => 'location_banner_right_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Aggiungi banner',
			'key' => 'field_5892023b9a1a3',
			'label' => 'Banner',
			'name' => 'location_banner',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-pages/location.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5890bf83cff0d',
	'title' => 'Opzioni',
	'fields' => array (
		array (
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
			'key' => 'field_5890c714540fd',
			'label' => 'Bottone',
			'name' => 'options_contact',
			'type' => 'page_link',
			'instructions' => 'Seleziona la pagina che verrà associata al bottone nel header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5890bfbea8760',
			'label' => 'Telefono',
			'name' => 'options_phone',
			'type' => 'text',
			'instructions' => 'Inserire il numero senza spazi, insieme al prefisso es. “+391234567890”.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5890c0aea8762',
			'label' => 'Email',
			'name' => 'options_email',
			'type' => 'text',
			'instructions' => 'Inserire la email es. “info@landhocoworking.com”.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5890c0daa8763',
			'label' => 'Indirizzo',
			'name' => 'options_address',
			'type' => 'text',
			'instructions' => 'Inserire indirizzo es. “Via del Corso 280, 00187 Rome Italy”.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5890c15aa8764',
			'label' => 'Facebook',
			'name' => 'options_facebook',
			'type' => 'text',
			'instructions' => 'Inserire url diretto alla pagina Facebook.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5890c171a8765',
			'label' => 'Instagram',
			'name' => 'options_instagram',
			'type' => 'text',
			'instructions' => 'Inserire url diretto al canale Instagram.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58930bba73e1b',
	'title' => 'Piani',
	'fields' => array (
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_58932d184dd00',
			'label' => 'Partners',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58932d8de5c13',
			'label' => 'Titolo',
			'name' => 'plans_banner_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
			'key' => 'field_58932da7e5c14',
			'label' => 'Testo',
			'name' => 'plans_banner_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
			'key' => 'field_58932dd23508d',
			'label' => 'Link',
			'name' => 'plans_banner_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'sub_fields' => array (
				array (
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'svg,png,jpg,jpeg,gif',
					'key' => 'field_589322371e5af',
					'label' => 'Immagine',
					'name' => 'plans_partners_image',
					'type' => 'file',
					'instructions' => 'Immagine a 1:1 con dimensioni 256x256px. Formati supportati: svg (consigliato), png, jpg, jpeg, gif',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_589323761e5b0',
					'label' => 'Titolo',
					'name' => 'plans_partners_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'placeholder' => '',
					'key' => 'field_58932d284dd01',
					'label' => 'Link',
					'name' => 'plans_partners_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Aggiungi partner',
			'collapsed' => 'field_589323761e5b0',
			'key' => 'field_589321ed1e5ae',
			'label' => 'Partners',
			'name' => 'plans_partners',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-pages/plans.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_589314f568898',
	'title' => 'Piano',
	'fields' => array (
		array (
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
			'key' => 'field_589339a20c8fc',
			'label' => 'Sottotitolo',
			'name' => 'plan_lead',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58933b676ac7d',
			'label' => 'Prezzo',
			'name' => 'plan_price',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'allow_multiple' => 0,
			'allow_null' => 0,
			'key' => 'field_58933d09d5cbc',
			'label' => 'Form',
			'name' => 'plan_form',
			'type' => 'gravity_forms_field',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'default_value' => '',
			'delay' => 0,
			'key' => 'field_58933c66df23a',
			'label' => 'Testo',
			'name' => 'plan_text',
			'type' => 'wysiwyg',
			'instructions' => 'Utilizzare la scala di partenza uguale o minore a H3 per i titoli',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'sub_fields' => array (
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_58933be0a7b90',
					'label' => 'Titolo',
					'name' => 'plan_features_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 2,
					'key' => 'field_58933bf1a7b91',
					'label' => 'Testo',
					'name' => 'plan_features_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi caratteristica',
			'collapsed' => 'field_58933be0a7b90',
			'key' => 'field_58933bbaa7b8f',
			'label' => 'Caratteristiche',
			'name' => 'plan_features',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => 'Evidenziare il piano corrente?',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_58933e71f47e7',
			'label' => 'Evidenziato',
			'name' => 'plan_featured',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'piano',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58921225b53bc',
	'title' => 'Servizi',
	'fields' => array (
		array (
			'sub_fields' => array (
				array (
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg,jpeg',
					'key' => 'field_5892127f50074',
					'label' => 'Immagine',
					'name' => 'services_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_5892125250072',
					'label' => 'Titolo',
					'name' => 'services_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 2,
					'key' => 'field_5892126450073',
					'label' => 'Testo',
					'name' => 'services_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Aggiungi servizio',
			'collapsed' => 'field_5892125250072',
			'key' => 'field_5892123450071',
			'label' => 'Servizi',
			'name' => 'services',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_589214f7f81a3',
			'label' => 'Banner',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => 'Abilitare il banner?',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_5892158454365',
			'label' => 'Banner',
			'name' => 'services_banner_if',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58921526aec0a',
			'label' => 'Titolo',
			'name' => 'services_banner_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5892158454365',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 2,
			'key' => 'field_58921546aec0b',
			'label' => 'Testo',
			'name' => 'services_banner_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5892158454365',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'allow_archives' => 0,
			'key' => 'field_58921555aec0c',
			'label' => 'Link',
			'name' => 'services_banner_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5892158454365',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-pages/services.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
